# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ismael/Gits/common-macros-c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ismael/Gits/common-macros-c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ismael/Gits/common-macros-c/CMakeFiles /home/ismael/Gits/common-macros-c/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ismael/Gits/common-macros-c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named macros-all-common

# Build rule for target.
macros-all-common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 macros-all-common
.PHONY : macros-all-common

# fast build rule for target.
macros-all-common/fast:
	$(MAKE) -f CMakeFiles/macros-all-common.dir/build.make CMakeFiles/macros-all-common.dir/build
.PHONY : macros-all-common/fast

#=============================================================================
# Target rules for targets named macros-endian-common

# Build rule for target.
macros-endian-common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 macros-endian-common
.PHONY : macros-endian-common

# fast build rule for target.
macros-endian-common/fast:
	$(MAKE) -f CMakeFiles/macros-endian-common.dir/build.make CMakeFiles/macros-endian-common.dir/build
.PHONY : macros-endian-common/fast

#=============================================================================
# Target rules for targets named macros-inttypes-common

# Build rule for target.
macros-inttypes-common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 macros-inttypes-common
.PHONY : macros-inttypes-common

# fast build rule for target.
macros-inttypes-common/fast:
	$(MAKE) -f CMakeFiles/macros-inttypes-common.dir/build.make CMakeFiles/macros-inttypes-common.dir/build
.PHONY : macros-inttypes-common/fast

src/macros-all-common.o: src/macros-all-common.cpp.o
.PHONY : src/macros-all-common.o

# target to build an object file
src/macros-all-common.cpp.o:
	$(MAKE) -f CMakeFiles/macros-all-common.dir/build.make CMakeFiles/macros-all-common.dir/src/macros-all-common.cpp.o
.PHONY : src/macros-all-common.cpp.o

src/macros-all-common.i: src/macros-all-common.cpp.i
.PHONY : src/macros-all-common.i

# target to preprocess a source file
src/macros-all-common.cpp.i:
	$(MAKE) -f CMakeFiles/macros-all-common.dir/build.make CMakeFiles/macros-all-common.dir/src/macros-all-common.cpp.i
.PHONY : src/macros-all-common.cpp.i

src/macros-all-common.s: src/macros-all-common.cpp.s
.PHONY : src/macros-all-common.s

# target to generate assembly for a file
src/macros-all-common.cpp.s:
	$(MAKE) -f CMakeFiles/macros-all-common.dir/build.make CMakeFiles/macros-all-common.dir/src/macros-all-common.cpp.s
.PHONY : src/macros-all-common.cpp.s

src/macros-endian-common.o: src/macros-endian-common.cpp.o
.PHONY : src/macros-endian-common.o

# target to build an object file
src/macros-endian-common.cpp.o:
	$(MAKE) -f CMakeFiles/macros-endian-common.dir/build.make CMakeFiles/macros-endian-common.dir/src/macros-endian-common.cpp.o
.PHONY : src/macros-endian-common.cpp.o

src/macros-endian-common.i: src/macros-endian-common.cpp.i
.PHONY : src/macros-endian-common.i

# target to preprocess a source file
src/macros-endian-common.cpp.i:
	$(MAKE) -f CMakeFiles/macros-endian-common.dir/build.make CMakeFiles/macros-endian-common.dir/src/macros-endian-common.cpp.i
.PHONY : src/macros-endian-common.cpp.i

src/macros-endian-common.s: src/macros-endian-common.cpp.s
.PHONY : src/macros-endian-common.s

# target to generate assembly for a file
src/macros-endian-common.cpp.s:
	$(MAKE) -f CMakeFiles/macros-endian-common.dir/build.make CMakeFiles/macros-endian-common.dir/src/macros-endian-common.cpp.s
.PHONY : src/macros-endian-common.cpp.s

src/macros-inttypes-common.o: src/macros-inttypes-common.cpp.o
.PHONY : src/macros-inttypes-common.o

# target to build an object file
src/macros-inttypes-common.cpp.o:
	$(MAKE) -f CMakeFiles/macros-inttypes-common.dir/build.make CMakeFiles/macros-inttypes-common.dir/src/macros-inttypes-common.cpp.o
.PHONY : src/macros-inttypes-common.cpp.o

src/macros-inttypes-common.i: src/macros-inttypes-common.cpp.i
.PHONY : src/macros-inttypes-common.i

# target to preprocess a source file
src/macros-inttypes-common.cpp.i:
	$(MAKE) -f CMakeFiles/macros-inttypes-common.dir/build.make CMakeFiles/macros-inttypes-common.dir/src/macros-inttypes-common.cpp.i
.PHONY : src/macros-inttypes-common.cpp.i

src/macros-inttypes-common.s: src/macros-inttypes-common.cpp.s
.PHONY : src/macros-inttypes-common.s

# target to generate assembly for a file
src/macros-inttypes-common.cpp.s:
	$(MAKE) -f CMakeFiles/macros-inttypes-common.dir/build.make CMakeFiles/macros-inttypes-common.dir/src/macros-inttypes-common.cpp.s
.PHONY : src/macros-inttypes-common.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... macros-inttypes-common"
	@echo "... macros-all-common"
	@echo "... macros-endian-common"
	@echo "... src/macros-all-common.o"
	@echo "... src/macros-all-common.i"
	@echo "... src/macros-all-common.s"
	@echo "... src/macros-endian-common.o"
	@echo "... src/macros-endian-common.i"
	@echo "... src/macros-endian-common.s"
	@echo "... src/macros-inttypes-common.o"
	@echo "... src/macros-inttypes-common.i"
	@echo "... src/macros-inttypes-common.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

